version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: iAiMjn7dM6kX72Ce
      POSTGRES_USER: user45L
      POSTGRES_DB: sampledb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  person-svc:
    build: .
    links:
      - postgres
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8080
      PG.USER: user45L
      PG.PASSWORD: iAiMjn7dM6kX72Ce
      PG.HOST: postgres
      PG.PORT: 5432
      PG.DBNAME: sampledb
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 8080:8080